# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lambent < Formula
  desc "File work into Lambent and close the questions loop, from your terminal."
  homepage "https://app.lambentlabs.ai"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tlg-studio/lambent/releases/download/v0.1.0/lambent_0.1.0_darwin_amd64.tar.gz"
      sha256 "6962928f56c04eca66018a3b3e6b291ae1028ebc004541e0a5657b4df4fdb33a"

      define_method(:install) do
        bin.install "lambent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tlg-studio/lambent/releases/download/v0.1.0/lambent_0.1.0_darwin_arm64.tar.gz"
      sha256 "e53c6fc16fae169bf13a25fe8222c5ca678b8ea608348ae2ed2125c33f6b6f21"

      define_method(:install) do
        bin.install "lambent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tlg-studio/lambent/releases/download/v0.1.0/lambent_0.1.0_linux_amd64.tar.gz"
      sha256 "387e0fc0bda4bdf45a0530f69f7ade2810d09dfc902ac8e196c197d085c442d7"
      define_method(:install) do
        bin.install "lambent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tlg-studio/lambent/releases/download/v0.1.0/lambent_0.1.0_linux_arm64.tar.gz"
      sha256 "b57c1cd5947414a73ccb3426b06847bc788b508e929b276bc7198a9fabc76378"
      define_method(:install) do
        bin.install "lambent"
      end
    end
  end

  test do
    system "#{bin}/lambent", "version"
  end
end
