# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lambent < Formula
  desc "File work into Lambent and close the questions loop, from your terminal."
  homepage "https://app.lambentlabs.ai"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tlg-studio/homebrew-tap/releases/download/v0.1.0/lambent_0.1.0_darwin_amd64.tar.gz"
      sha256 "781af985ddd1a9d470df29613b2b02d9b21b1fbd927c2c3db4873b84bc743f58"

      define_method(:install) do
        bin.install "lambent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tlg-studio/homebrew-tap/releases/download/v0.1.0/lambent_0.1.0_darwin_arm64.tar.gz"
      sha256 "33399de2616311cbd18ff3cce003346c766fa219cd2a4b25ad8610ae8554ffe9"

      define_method(:install) do
        bin.install "lambent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tlg-studio/homebrew-tap/releases/download/v0.1.0/lambent_0.1.0_linux_amd64.tar.gz"
      sha256 "aa1cbf85772a039dcf31cf0dd54154f4a175910ad7eb2ec6cf146f2d10008ce9"
      define_method(:install) do
        bin.install "lambent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tlg-studio/homebrew-tap/releases/download/v0.1.0/lambent_0.1.0_linux_arm64.tar.gz"
      sha256 "4de182b57075137f9a41493d58d1dde73e040fcf7de1b7a1cf3639dc993182a0"
      define_method(:install) do
        bin.install "lambent"
      end
    end
  end

  test do
    system "#{bin}/lambent", "version"
  end
end
