# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lambent < Formula
  desc "File work into Lambent and close the questions loop, from your terminal."
  homepage "https://app.lambentlabs.ai"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tlg-studio/homebrew-tap/releases/download/v0.2.0/lambent_0.2.0_darwin_amd64.tar.gz"
      sha256 "0689e301a1f61f67c167d0605bcf794aea310ec7b05af0de4d83ebd1cc0dcb11"

      define_method(:install) do
        bin.install "lambent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tlg-studio/homebrew-tap/releases/download/v0.2.0/lambent_0.2.0_darwin_arm64.tar.gz"
      sha256 "f1685b2a1c4933a292ae2623b70aa0f147c197b53a95de211cdcdb8418015560"

      define_method(:install) do
        bin.install "lambent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tlg-studio/homebrew-tap/releases/download/v0.2.0/lambent_0.2.0_linux_amd64.tar.gz"
      sha256 "0b5ee27f5aa9293787bd6776fb7b5ee750d137c8513db78770daf29886b8a6a8"
      define_method(:install) do
        bin.install "lambent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tlg-studio/homebrew-tap/releases/download/v0.2.0/lambent_0.2.0_linux_arm64.tar.gz"
      sha256 "63f0c0af796f7e914447a6d42574a0cbbd503dc7b924e9de61164148dce35584"
      define_method(:install) do
        bin.install "lambent"
      end
    end
  end

  test do
    system "#{bin}/lambent", "version"
  end
end
